name: Deploy to Yegara Host

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync files to Yegara Host via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout Repository
        uses: actions/checkout@v4

      - name: 📂 Sync Files to Yegara cPanel Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_TARGET_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            backend/.env
